version: "3.9"

services:
  limesurvey:
    image: martialblog/limesurvey:5-fpm
    volumes:
      - ./surveys:/var/www/html/upload/surveys
      - ./themes:/var/www/html/upload/themes/survey
      - lime:/var/www/html
    env_file:
      - .env

  lime-web:
    image: nginx:alpine
    profiles: ["local"]
    links:
      - limesurvey
    depends_on:
      - limesurvey
    ports:
      - "8085:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - lime:/var/www/html

  lime-db:
    image: mysql:5.7
    profiles: ["db"]
    env_file:
      - .env

volumes:
  lime: